# Generated by Django 3.1.7 on 2021-02-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='language',
            name='paradigm',
            field=models.CharField(max_length=50),
        ),
    ]
